### ISSUE TITLE
V2EX 的帐号密码泄露了

### ISSUE THREAD

**Issue by gexiao** [zhiyue-archive/zhiyue_tools#1]
![image](https://cloud.githubusercontent.com/assets/3390634/22174801/db3bc78c-e021-11e6-9336-59e3ca663e96.png)

https://github.com/zhiyue/zhiyue_tools/blob/develop/pyutils/login_v2ex.py#L16

@zhiyue

**Comment by zhiyue** [comment]
感谢提醒！🤣🤣
